name: Build and Upload Artifact

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Verify build output
        run: ls -la .next

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build-${{ matrix.node-version }}
          path: .next

